apiVersion: v2
name: unikorn-core
description: A Helm chart for deploying Unikorn Core

type: application

version: 1.14.0
appVersion: 1.14.0

icon: https://assets.unikorn-cloud.org/images/logos/dark-on-light/icon.svg

dependencies:
- name: unikorn-common
  version: 0.1.16
  repository: https://nscaledev.github.io/uni-helm-common
